### ISSUE TITLE
Problema de no saber mi id

### ISSUE THREAD

**Issue by FrancoLiberali** [taller2fiuba/chotuve-android-client#14]
Cuando toco en un comentario de un video me lleva al perfil de un usuario
Si el comentario es mio me va a llevar a mi perfil pero me lo va mostrar como si fuera otro, voy a tener el boton de agregar a contactos. Todo esto porque no se mi id de usuario entonces no puedo saber que ese soy yo.
Tambien cuando comento algo nuevo y meto ese comentario en los comentarios, como no se quien soy no se que datos poner. Bueno este si se puede resolver porque puedo obtener mis datos asi como los obtengo en mi perfil, pero si pongo mis datos tengo el mismo problema que arriba

**Comment by edjus** [comment]
Se podríá resolver que al momento de loguearse además del token te devuelva el id y solo lo usas cuando sea necesario, pero no se que tan bueno sea hacer ésto.
