### ISSUE TITLE
Mandar en todos los requests al app server el token

### ISSUE THREAD

**Issue by FrancoLiberali** [taller2fiuba/chotuve-android-client#4]
La opcion del token con el flujo que todavia no esta confirmado ya esta hecho, hay que mandar ese token en todos los requests. Yo lo haria en AppServerService

**Comment by FrancoLiberali** [comment]
El flujo cambio pero esto sigue en pie, cuando me registro o me logeo se me devuelve un token. Ese token hay que guardarlo y luego enviarlo en cada request. Eliminar todo el codigo para obtener el token de firebase

**Comment by sportelliluciano** [comment]
Cierro esto porque la interfaz de esta lógica ya está incorporada en el modelo.
