### ISSUE TITLE
Hacer registro y login a mano (solo email-pass)

### ISSUE THREAD

**Issue by FrancoLiberali** [taller2fiuba/chotuve-android-client#5]
Como la autentificacion va a ser en el auth server y no en firebase, tenemos que hacer las pantallas a mano. Hay que pegarle a los endpoints del app server

**Comment by FrancoLiberali** [comment]
rama login

**Comment by FrancoLiberali** [comment]
rama: registro_y_login

**Comment by sportelliluciano** [comment]
Renombro el issue porque además de la pantalla tiene que estar el código para cerrar el PR con una funcionalidad.

**Comment by sportelliluciano** [comment]
Cierro esto que ya fue mergeado a master.
